version: 0.1.0-BUILD{build}
image: Visual Studio 2017
before_build:
  - nuget restore
configuration:
  - Release
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
  project: aerogear-xamarin-sdk.sln
test: on
