using System;
using System.IO;
using Android.Content;
using Android.OS;
using Java.Lang;

namespace AeroGear.Mobile.Security.Checks
{
    /// <summary>
    /// A check for whether the device the application is running on is rooted.
    /// </summary>
    public class NonRootedCheck : AbstractSecurityCheck
    {
        protected override string Name => "Rooted Check";

        private readonly Context context;

        public NonRootedCheck(Context ctx)
        {
            this.context = ctx;
        }

        /// <summary>
        /// Solution found at https://stackoverflow.com/a/8097801.
        /// </summary>
        /// <returns>The check.</returns>
        public override SecurityCheckResult Check()
        {
            bool rooted = CheckForTestKeys() || CheckForSuBinary() || CheckSuExists();
            return new SecurityCheckResult(this, !rooted);
        }

        /// <summary>
        /// Checks if custom key generated by third-party developer was used to
        /// sign kernel when it was compiled.
        /// </summary>
        /// <returns><c>true</c>, if custom key was used, <c>false</c> otherwise.</returns>
        private bool CheckForTestKeys()
        {
            string buildTags = Build.Tags;
            return buildTags != null && buildTags.Contains("test-keys");
        }

        /// <summary>
        /// Checks various common locations for the SU binary.
        /// </summary>
        /// <returns><c>true</c>, if SU found, <c>false</c> otherwise.</returns>
        private bool CheckForSuBinary()
        {
            string[] paths = { "/system/app/Superuser.apk", "/sbin/su",
                "/system/bin/su", "/system/xbin/su", "/data/local/xbin/su",
                "/data/local/bin/su", "/system/sd/xbin/su",
                "/system/bin/failsafe/su", "/data/local/su", "/su/bin/su"};
            foreach (string path in paths)
            {
                if (File.Exists(path)) return true;
            }
            return false;
        }

        /// <summary>
        /// Check that su exists with "which su" command.
        /// </summary>
        /// <returns><c>true</c>, if su exists, <c>false</c> otherwise.</returns>
        private bool CheckSuExists()
        {
            Java.Lang.Process process = null;
            try
            {
                process = Runtime.GetRuntime().Exec(new string[] { "/system/xbin/which", "su" });
                Java.IO.BufferedReader input = new Java.IO.BufferedReader(
                    new Java.IO.InputStreamReader(process.InputStream));
                if (input.ReadLine() != null) return true;
                return false;
            }
            catch (Throwable)
            {
                return false;
            }
            finally
            {
                if (process != null) process.Destroy();
            }
        }
    }
}
