#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Auth.Platform.Android.Tests.Resource", IsApplication=true)]

namespace Auth.Platform.Android.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::Auth.Platform.Android.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::Auth.Platform.Android.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::Auth.Platform.Android.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::Auth.Platform.Android.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::Auth.Platform.Android.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::Auth.Platform.Android.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::Auth.Platform.Android.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::Auth.Platform.Android.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::Auth.Platform.Android.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::Auth.Platform.Android.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::Auth.Platform.Android.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::Auth.Platform.Android.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::Auth.Platform.Android.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::Auth.Platform.Android.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::Auth.Platform.Android.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::Auth.Platform.Android.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::Auth.Platform.Android.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::Auth.Platform.Android.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::Auth.Platform.Android.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::Auth.Platform.Android.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::Auth.Platform.Android.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::Auth.Platform.Android.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int notification_action_color_filter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int notification_icon_bg_color = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int notification_material_background_media_default_color = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primary_text_default_material_dark = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int ripple_material_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int secondary_text_default_material_dark = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int secondary_text_default_material_light = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0020
			public const int OptionHostName = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int OptionPort = 2131427361;
			
			// aapt resource value: 0x7f0b001f
			public const int OptionRemoteServer = 2131427359;
			
			// aapt resource value: 0x7f0b002f
			public const int OptionsButton = 2131427375;
			
			// aapt resource value: 0x7f0b002a
			public const int ResultFullName = 2131427370;
			
			// aapt resource value: 0x7f0b002c
			public const int ResultMessage = 2131427372;
			
			// aapt resource value: 0x7f0b002b
			public const int ResultResultState = 2131427371;
			
			// aapt resource value: 0x7f0b0029
			public const int ResultRunSingleMethodTest = 2131427369;
			
			// aapt resource value: 0x7f0b002d
			public const int ResultStackTrace = 2131427373;
			
			// aapt resource value: 0x7f0b0025
			public const int ResultsFailed = 2131427365;
			
			// aapt resource value: 0x7f0b0022
			public const int ResultsId = 2131427362;
			
			// aapt resource value: 0x7f0b0026
			public const int ResultsIgnored = 2131427366;
			
			// aapt resource value: 0x7f0b0027
			public const int ResultsInconclusive = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int ResultsMessage = 2131427368;
			
			// aapt resource value: 0x7f0b0024
			public const int ResultsPassed = 2131427364;
			
			// aapt resource value: 0x7f0b0023
			public const int ResultsResult = 2131427363;
			
			// aapt resource value: 0x7f0b002e
			public const int RunTestsButton = 2131427374;
			
			// aapt resource value: 0x7f0b0030
			public const int TestSuiteListView = 2131427376;
			
			// aapt resource value: 0x7f0b000e
			public const int action0 = 2131427342;
			
			// aapt resource value: 0x7f0b000b
			public const int action_container = 2131427339;
			
			// aapt resource value: 0x7f0b0012
			public const int action_divider = 2131427346;
			
			// aapt resource value: 0x7f0b000c
			public const int action_image = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int action_text = 2131427341;
			
			// aapt resource value: 0x7f0b001c
			public const int actions = 2131427356;
			
			// aapt resource value: 0x7f0b0006
			public const int async = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int blocking = 2131427335;
			
			// aapt resource value: 0x7f0b000f
			public const int cancel_action = 2131427343;
			
			// aapt resource value: 0x7f0b0017
			public const int chronometer = 2131427351;
			
			// aapt resource value: 0x7f0b001e
			public const int end_padder = 2131427358;
			
			// aapt resource value: 0x7f0b0008
			public const int forever = 2131427336;
			
			// aapt resource value: 0x7f0b0019
			public const int icon = 2131427353;
			
			// aapt resource value: 0x7f0b001d
			public const int icon_group = 2131427357;
			
			// aapt resource value: 0x7f0b0018
			public const int info = 2131427352;
			
			// aapt resource value: 0x7f0b0009
			public const int italic = 2131427337;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0011
			public const int media_actions = 2131427345;
			
			// aapt resource value: 0x7f0b000a
			public const int normal = 2131427338;
			
			// aapt resource value: 0x7f0b001b
			public const int notification_background = 2131427355;
			
			// aapt resource value: 0x7f0b0014
			public const int notification_main_column = 2131427348;
			
			// aapt resource value: 0x7f0b0013
			public const int notification_main_column_container = 2131427347;
			
			// aapt resource value: 0x7f0b001a
			public const int right_icon = 2131427354;
			
			// aapt resource value: 0x7f0b0015
			public const int right_side = 2131427349;
			
			// aapt resource value: 0x7f0b0010
			public const int status_bar_latest_event_content = 2131427344;
			
			// aapt resource value: 0x7f0b0002
			public const int tag_transition_group = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int text2 = 2131427332;
			
			// aapt resource value: 0x7f0b0016
			public const int time = 2131427350;
			
			// aapt resource value: 0x7f0b0005
			public const int title = 2131427333;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int notification_action = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action_tombstone = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_media_action = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_media_cancel_action = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_big_media = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_big_media_custom = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_big_media_narrow = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_big_media_narrow_custom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_custom_big = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_icon_group = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_lines_media = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_media = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_media_custom = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_part_chronometer = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_part_time = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int options = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int results = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int test_result = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int test_suite = 2130968594;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int status_bar_notification_info_overflow = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050005
			public const int TextAppearance_Compat_Notification = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int TextAppearance_Compat_Notification_Info = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int TextAppearance_Compat_Notification_Media = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int TextAppearance_Compat_Notification_Time = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int TextAppearance_Compat_Notification_Title = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int Widget_Compat_NotificationActionContainer = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Widget_Compat_NotificationActionText = 2131034122;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
